language: bash
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/avr-tools    
install: true

stages:
  - check sizes
  - test

env:
  global:
#    - TOOLS_VERSION=1.0.6
#    - TOOLS_VERSION=1.6.9
#    - TOOLS_VERSION=1.6.13
#    - TOOLS_VERSION=1.8.5
    - TOOLS_VERSION=1.8.7
#    - TOOLS_VERSION=microchip
  matrix:
    - OPTIBOOT_TARGET=atmega128
    - OPTIBOOT_TARGET=atmega1280
    - OPTIBOOT_TARGET=atmega1281
    - OPTIBOOT_TARGET=atmega1284
    - OPTIBOOT_TARGET=atmega1284p
    - OPTIBOOT_TARGET=atmega128a
    - OPTIBOOT_TARGET=atmega16
    - OPTIBOOT_TARGET=atmega162
    - OPTIBOOT_TARGET=atmega164
    - OPTIBOOT_TARGET=atmega164a
    - OPTIBOOT_TARGET=atmega164p
    - OPTIBOOT_TARGET=atmega164pa
    - OPTIBOOT_TARGET=atmega168
    - OPTIBOOT_TARGET=atmega168a
    - OPTIBOOT_TARGET=atmega168p
    - OPTIBOOT_TARGET=atmega168pa
    - OPTIBOOT_TARGET="atmega168pb LED=B5"
    - OPTIBOOT_TARGET=atmega169
    - OPTIBOOT_TARGET=atmega169a
    - OPTIBOOT_TARGET=atmega169p
    - OPTIBOOT_TARGET=atmega169pa
    - OPTIBOOT_TARGET=atmega16a
    - OPTIBOOT_TARGET=atmega2560
    - OPTIBOOT_TARGET=atmega2561
    - OPTIBOOT_TARGET=atmega32
    - OPTIBOOT_TARGET=atmega324
    - OPTIBOOT_TARGET=atmega324a
    - OPTIBOOT_TARGET=atmega324p
    - OPTIBOOT_TARGET=atmega324pa
    - OPTIBOOT_TARGET=atmega324pb
    - OPTIBOOT_TARGET=atmega328
    - OPTIBOOT_TARGET=atmega328_pro8
    - OPTIBOOT_TARGET="atmega328 BIGBOOT=1"
    - OPTIBOOT_TARGET="atmega328 LED_START_FLASHES=0 LED_START_ON=1 SUPPORT_EEPROM=1"
    - OPTIBOOT_TARGET="atmega328 LED_START_FLASHES=0 SUPPORT_EEPROM=1"
    - OPTIBOOT_TARGET="atmega328 LED_START_FLASHES=0"
    - OPTIBOOT_TARGET="atmega328 SOFT_UART=1"
    - OPTIBOOT_TARGET="atmega328pb LED=B5"
    - OPTIBOOT_TARGET=atmega329
    - OPTIBOOT_TARGET=atmega3290
    - OPTIBOOT_TARGET=atmega3290p
    - OPTIBOOT_TARGET=atmega3290pa
    - OPTIBOOT_TARGET=atmega329a
    - OPTIBOOT_TARGET=atmega329p
    - OPTIBOOT_TARGET=atmega329pa
    - OPTIBOOT_TARGET=atmega64
    - OPTIBOOT_TARGET=atmega640
    - OPTIBOOT_TARGET=atmega644p
    - OPTIBOOT_TARGET=atmega649
    - OPTIBOOT_TARGET=atmega6490
    - OPTIBOOT_TARGET=atmega6490p
    - OPTIBOOT_TARGET=atmega649p
    - OPTIBOOT_TARGET=atmega64a
    - OPTIBOOT_TARGET=atmega8
    - OPTIBOOT_TARGET=atmega8515
    - OPTIBOOT_TARGET=atmega8535
    - OPTIBOOT_TARGET=atmega88
    - OPTIBOOT_TARGET="atmega88p LED=B5"
    - OPTIBOOT_TARGET="atmega88pa LED=B5"
    - OPTIBOOT_TARGET="atmega88pb LED=B5"
    - OPTIBOOT_TARGET=attiny1634
    - OPTIBOOT_TARGET=attiny1634at110
    - OPTIBOOT_TARGET=attiny1634at110ser1
    - OPTIBOOT_TARGET=attiny1634at12
    - OPTIBOOT_TARGET=attiny1634at12ser1
    - OPTIBOOT_TARGET=attiny1634at147
    - OPTIBOOT_TARGET=attiny1634at147ser1
    - OPTIBOOT_TARGET=attiny1634at16
    - OPTIBOOT_TARGET=attiny1634at16ser1
    - OPTIBOOT_TARGET=attiny1634at737
    - OPTIBOOT_TARGET=attiny1634at737ser1
    - OPTIBOOT_TARGET=attiny1634at8
    - OPTIBOOT_TARGET=attiny1634at8_5v
    - OPTIBOOT_TARGET=attiny1634at8_5vser1
    - OPTIBOOT_TARGET=attiny1634at8ser1
    - OPTIBOOT_TARGET=attiny1634at921
    - OPTIBOOT_TARGET=attiny1634at921ser1
    - OPTIBOOT_TARGET=attiny167
    - OPTIBOOT_TARGET=attiny828
    - OPTIBOOT_TARGET=attiny828at8
    - OPTIBOOT_TARGET=attiny828at8_5v
    - OPTIBOOT_TARGET=attiny84
    - OPTIBOOT_TARGET=attiny841
    - OPTIBOOT_TARGET=attiny841at110
    - OPTIBOOT_TARGET=attiny841at110ser1
    - OPTIBOOT_TARGET=attiny841at12
    - OPTIBOOT_TARGET=attiny841at12ser1
    - OPTIBOOT_TARGET=attiny841at147
    - OPTIBOOT_TARGET=attiny841at147ser1
    - OPTIBOOT_TARGET=attiny841at16
    - OPTIBOOT_TARGET=attiny841at16noLED
    - OPTIBOOT_TARGET=attiny841at16ser1
    - OPTIBOOT_TARGET=attiny841at184
    - OPTIBOOT_TARGET=attiny841at184ser1
    - OPTIBOOT_TARGET=attiny841at20
    - OPTIBOOT_TARGET=attiny841at20noLED
    - OPTIBOOT_TARGET=attiny841at20ser1
    - OPTIBOOT_TARGET=attiny841at737
    - OPTIBOOT_TARGET=attiny841at737ser1
    - OPTIBOOT_TARGET=attiny841at8
    - OPTIBOOT_TARGET=attiny841at8_5v
    - OPTIBOOT_TARGET=attiny841at8noLED
    - OPTIBOOT_TARGET=attiny841at8ser1
    - OPTIBOOT_TARGET=attiny841at921
    - OPTIBOOT_TARGET=attiny841at921ser1
    - OPTIBOOT_TARGET=attiny87
    - OPTIBOOT_TARGET=bobuino
    - OPTIBOOT_TARGET=diecimila
    - OPTIBOOT_TARGET=lilypad
    - OPTIBOOT_TARGET=lilypad_resonator
    - OPTIBOOT_TARGET=luminet
    - OPTIBOOT_TARGET=mega1280
    - OPTIBOOT_TARGET=mega2560
    - OPTIBOOT_TARGET=mighty1284
    - OPTIBOOT_TARGET=pro16
    - OPTIBOOT_TARGET=pro20
    - OPTIBOOT_TARGET=pro8
    - OPTIBOOT_TARGET=sanguino
    - OPTIBOOT_TARGET=virboot328
    - OPTIBOOT_TARGET=virboot8
    - OPTIBOOT_TARGET=wildfire
    - OPTIBOOT_TARGET=wildfirev2
    - OPTIBOOT_TARGET=wildfirev3
    - OPTIBOOT_TARGET=xplained168pb
    - OPTIBOOT_TARGET=xplained328p
    - OPTIBOOT_TARGET=xplained328pb

matrix:
  allow_failures:
    - env: OPTIBOOT_TARGET="atmega328 LED_START_FLASHES=0 LED_START_ON=1 SUPPORT_EEPROM=1"
    - env: OPTIBOOT_TARGET="atmega328 LED_START_FLASHES=0 SUPPORT_EEPROM=1"

script: scripts/travis-build.sh $TOOLS_VERSION $OPTIBOOT_TARGET

jobs:
  include:
    - stage: check sizes
      script: scripts/travis-check-sizes.sh
      env: OPTIBOOT_TARGET=none

notifications:
  email:
    on_success: always
    on_failure: always
 